### ISSUE TITLE
how to use it 

### ISSUE THREAD

**Issue by r00t7oo2jm** [ORCx41/TerraLdr#1]
bro how to use it

**Comment by ORCx41** [comment]
@r00t7oo2jm you need visual studio to compile it...
first you need to compile [GenerateRsrc](https://github.com/ORCx41/TerraLdr/tree/main/Helper/GenerateRsrc), then use it to generate DataFile.terra file (that's your encrypted payload) you can drag it to [here](https://github.com/ORCx41/TerraLdr/tree/main/Terra) after its generated and compile terra project, Terra.exe is your loader
